name: Publish package to GitHub Packages
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org/'
          scope: '@tanand-tech'
      - run: npm ci
      - run: npm publish --public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
